# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: zpng 0.4.5 ruby lib

Gem::Specification.new do |s|
  s.name = "zpng".freeze
  s.version = "0.4.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Andrey \"Zed\" Zaikin".freeze]
  s.date = "2023-02-19"
  s.email = "zed.0xff@gmail.com".freeze
  s.executables = ["zpng".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
    "README.md.tpl",
    "TODO"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "README.md.tpl",
    "Rakefile",
    "TODO",
    "VERSION",
    "bin/zpng",
    "lib/zpng.rb",
    "lib/zpng/adam7_decoder.rb",
    "lib/zpng/block.rb",
    "lib/zpng/bmp/reader.rb",
    "lib/zpng/chunk.rb",
    "lib/zpng/cli.rb",
    "lib/zpng/color.rb",
    "lib/zpng/deep_copyable.rb",
    "lib/zpng/hexdump.rb",
    "lib/zpng/image.rb",
    "lib/zpng/metadata.rb",
    "lib/zpng/pixels.rb",
    "lib/zpng/readable_struct.rb",
    "lib/zpng/scan_line.rb",
    "lib/zpng/scan_line/mixins.rb",
    "lib/zpng/string_ext.rb",
    "lib/zpng/text_chunk.rb",
    "misc/chars.png",
    "misc/gen_ascii_map.rb",
    "spec/adam7_spec.rb",
    "spec/alpha_spec.rb",
    "spec/ascii_spec.rb",
    "spec/bad_samples_spec.rb",
    "spec/bmp_spec.rb",
    "spec/cli_spec.rb",
    "spec/color_spec.rb",
    "spec/create_image_spec.rb",
    "spec/crop_spec.rb",
    "spec/deinterlace_spec.rb",
    "spec/exception_spec.rb",
    "spec/image_spec.rb",
    "spec/load_save_spec.rb",
    "spec/metadata_spec.rb",
    "spec/modify_spec.rb",
    "spec/pixel_access_spec.rb",
    "spec/pixels_enumerator_spec.rb",
    "spec/running_pixel_spec.rb",
    "spec/set_random_pixel_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/png_suite.rb",
    "zpng.gemspec"
  ]
  s.homepage = "http://github.com/zed-0xff/zpng".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.3.7".freeze
  s.summary = "pure ruby PNG file manipulation & validation".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<rainbow>.freeze, ["~> 3.1.1"])
    s.add_development_dependency(%q<rspec>.freeze, ["~> 3.11.0"])
    s.add_development_dependency(%q<rspec-its>.freeze, ["~> 1.3.0"])
    s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.4.9"])
  else
    s.add_dependency(%q<rainbow>.freeze, ["~> 3.1.1"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3.11.0"])
    s.add_dependency(%q<rspec-its>.freeze, ["~> 1.3.0"])
    s.add_dependency(%q<juwelier>.freeze, ["~> 2.4.9"])
  end
end

